"""Pilgrim facility directory supplied for the project; verify with TTD before production release."""
FACILITIES = [
 {"kind":"restroom","name":"Restrooms & drinking water","locations":"PAC I–V, VQC I & II, Kalyanakatta, and Jala Prasadam RO kiosks on the temple ring road.","details":"350+ permanent and institutional toilet blocks; 24/7 sanitation cycles. Free purified drinking water and milk points operate continuously.","latitude":13.6839,"longitude":79.3476},
 {"kind":"food","name":"Food & Annaprasadam","locations":"Matrusri Tarigonda Vengamamba Annaprasada Complex (MTVAC), VQC compartments, PAC II, Rambagicha Bus Stand, and CRO.","details":"Free meals and beverages for approximately 55,000–65,000+ pilgrims daily; waiting compartments receive milk and refreshments every 3 hours.","latitude":13.6842,"longitude":79.3481},
 {"kind":"medical","name":"Medical facilities","locations":"Aswini Hospital near Seshadri Nagar, Tirumala, and emergency aid stations on Alipiri and Srivari Mettu footpaths.","details":"24/7 emergency care, trauma response, and ambulance coordination. TTD helpline: 155257.","latitude":13.6825,"longitude":79.3450},
 {"kind":"laddu","name":"Laddu counters & kiosks","locations":"Main Laddu Complex on West/East Mada Street, VQC exit, MBC smart kiosks, and standard laddu stalls.","details":"Service is stated as 24/7. One free laddu per darshan token; additional laddus and self-service limits must be confirmed at the counter.","latitude":13.6850,"longitude":79.3490},
 {"kind":"phone","name":"Phone & mobile deposit centres","locations":"Opposite VQC I & II, PAC-3, PAC-5 (Venkatadri Nilayam), and near Sarva/Special Entry darshan lines.","details":"Mobile phones are prohibited inside the temple. Collection is described at PAC IV (Old Annadhanam Complex) or designated hubs using a receipt token. Confirm current locker rules on arrival.","latitude":13.6845,"longitude":79.3470},
 {"kind":"wheelchair","name":"Wheelchair assistance","locations":"Medical centers, temple help desks, and PAC complexes.","details":"Free wheelchair assistance for senior citizens, differently abled devotees, and patients. Request at medical centers or help desks.","latitude":13.6830,"longitude":79.3465},
 {"kind":"water","name":"Drinking water points","locations":"Queue lines, Mada Streets, Annaprasadam Complex, bus stand, PAC complexes, and footpaths.","details":"Free purified drinking water points throughout the area. Volunteers distribute water during peak seasons.","latitude":13.6835,"longitude":79.3480},
 {"kind":"navigation","name":"Navigation points","locations":"Srivari Temple, CRO, PAC-1 to PAC-5, Bus Stand, Annaprasadam Complex, Laddu Counters, Accommodation Centers, Medical Centers, and Parking.","details":"Navigate to important locations using Google Maps integration.","latitude":13.6855,"longitude":79.3495},
]
